# Generated by Django 5.1.6 on 2025-02-18 07:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('commentaire', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('sexe', models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme')], default='', max_length=10)),
                ('ville', models.CharField(blank=True, default='Douala', max_length=255)),
                ('mot_de_passe', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('telephone', models.BigIntegerField(null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.proprietaire')),
            ],
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_maison', models.CharField(choices=[('APPARTEMENT', 'Appartement'), ('VILLA', 'Villa'), ('MAISON_DE_CAMPAGNE', 'Maison de campagne'), ('MAISON_DE_VILLE', 'Maison de ville'), ('STUDIO', 'Studio')], max_length=100)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=10)),
                ('localisation', models.CharField(max_length=255)),
                ('nombre_de_chambre', models.IntegerField(blank=True, null=True)),
                ('nombre_de_douche', models.IntegerField(blank=True, null=True)),
                ('nombre_de_cuisine', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('photo_douche', models.ImageField(blank=True, null=True, upload_to='media/douches/')),
                ('photo_chambre', models.ImageField(blank=True, null=True, upload_to='media/chambres/')),
                ('photo_cuisine', models.ImageField(blank=True, null=True, upload_to='media/cuisines/')),
                ('photo_salon', models.ImageField(blank=True, null=True, upload_to='media/salons/')),
                ('is_published', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('libre', 'Libre'), ('occupee', 'Occupée')], default='libre', max_length=10)),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.proprietaire')),
            ],
            options={
                'permissions': [('can_create_maison', 'Peut créer des maisons'), ('can_modify_maison', 'Peut modifier des maisons'), ('can_publish_maison', 'Peut publier des maisons')],
            },
        ),
    ]
