# Generated by Django 5.1.6 on 2025-02-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='preciser_la_localisation_de_votre_maison',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
