# Generated by Django 5.1.6 on 2025-03-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_maison_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='is_masque',
            field=models.BooleanField(default=False),
        ),
    ]
