# Generated by Django 5.1.6 on 2025-03-02 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_proprietaire_is_masque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proprietaire',
            old_name='is_masque',
            new_name='is_suppression_temporaire',
        ),
    ]
