# Generated by Django 5.1.6 on 2025-03-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_is_masque_proprietaire_is_suppression_temporaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='is_masque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='is_suppression_temporaire',
            field=models.BooleanField(default=True),
        ),
    ]
