# Generated by Django 5.1.6 on 2025-03-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_proprietaire_is_masque_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietaire',
            name='is_suppression_temporaire',
        ),
        migrations.AlterField(
            model_name='maison',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
