# Generated by Django 5.1.6 on 2025-03-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_proprietaire_is_suppression_temporaire_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proprietaire',
            old_name='is_masque',
            new_name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='maison',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='maison',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
